### ISSUE TITLE
Possibly mention webpack providing fetch-everywhere in readme

### ISSUE THREAD

**Issue by johncip** [clubhouse/clubhouse-lib#22]
Hey Clubhouse, just a heads up / possible documentation request.

I found that in order to actually use the `fetch-everywhere` dependency, I had to add this to my webpack config:

```javascript
  plugins: [
    ...
    new webpack.ProvidePlugin({
      'fetch': 'fetch-everywhere'
    }),
   ]
```

Without it, the fetch calls would fail in the browser. The fetch-everywhere docs don't mention this step either.

This might be obvious to someone who is less new to webpack projects than me, and if so, feel free to ignore. But I mention this in case you think it's worth adding to the readme for others. (Or if there's a better way to include fetch-everywhere in-browser.)

**Comment by eliperkins** [comment]
Ah, I'm not as familiar with webpack, so this is news to me too! If you'd like to PR an addition to the README about this, I'd love to get it in.
