### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by eliperkins** [clubhouse/clubhouse-lib#36]
Currently, the README is very sparse and doesn't provide too much information on how to get started.

We should improve this by adding information in the following outline:

1. Header (`# Clubhouse JavaScript SDK` or something like that)
    * description ("A library for interacting with the Clubhouse REST API")
1. Getting Started
    * requirements
    * install instructions
    * how to get an API token
1. Usage
    * how the thing actually works
1. Documentation
    * link to https://clubhouse.io/api for complete REST API documentation
    * autogenerated documentation from existing methods?

**Comment by charpeni** [comment]
👋Hey @eliperkins,

I think we did a great job with the new README by covering the installation, how to get an API token, and by providing a CodeSandbox.

While they're always room for improvement, I'm going to close this issue.
