### ISSUE TITLE
`create` not callable from Typescript

### ISSUE THREAD

**Issue by chpspiir** [clubhouse/clubhouse-lib#37]
I wanted to use this library from Typescript and it seems the typings do not allow Clubhouse.create to be called like in the example in the README.

This is my work around:
```
import Clubhouse from 'clubhouse-lib';
import {create} from 'clubhouse-lib';

export function generateClubHouseReport(apiKey: string) {
    const client = create(apiKey); // Compiles
    const fail = Clubhouse.create(apiKey); // Does not
}
```

This doesn't seem intentional.

**Comment by chpspiir** [comment]
I see that I should probably have used this to import Clubhouse:
`import * as Clubhouse from 'clubhouse-lib';`

Maybe a Typescript example would fix that confusion. I'll see if I can't extend the README to include this.

**Comment by eliperkins** [comment]
Ooh, nice find @chpspiir. Admittedly, we don't use this library from TypeScript here at Clubhouse, so we haven't run into this yet.

The `create` method is defined here: https://github.com/clubhouse/clubhouse-lib/blob/540abbfe82cc5d06caae9b73468a455cee72572d/typings/index.d.ts#L46, however, I'm not super clear on how type definitions for modules works.

I'd love for this to be clearer for future TypeScript users, either by updating the README or improving the type definition!

**Comment by chpspiir** [comment]
The above fix that I posted ended up not working anyway. So the issue still stands 🤔 

I am at the same place as you with regards to the type definitions. I tried looking, but I kinda gave up when I found a work-around.

**Comment by eliperkins** [comment]
It looks like @j-martin is successfully using `Clubhouse.create` in their TypeScript project: https://github.com/andjosh/clubhouse-cli/blob/d63af74a6129c5cbf306c5cf15cfbc490bb1bc56/src/lib/client.ts#L1-L12

@chpspiir would you mind putting together a repro case for this, hopefully as a failing test in a PR to this project, so that we can address it for you?

**Comment by chpspiir** [comment]
Sorry, it does indeed work. Sorry about the confusion 😓

**Comment by eliperkins** [comment]
No worries! Happy to have folks using the library. Feel free to reach out or open other issues if you have more questions.
