### ISSUE TITLE
Works only against the beta API 

### ISSUE THREAD

**Issue by janwiberg-dfds** [clubhouse/clubhouse-lib#50]
As can be seen when actually trying to use it and finding that it connects with missing or broken endpoints 
`Error: Bad Request
    at new ClientError ([redacted]/node_modules/clubhouse-lib/build/client_error.js:19:112)
    at [redacted]/node_modules/clubhouse-lib/build/FetchRequestParser.js:26:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: Body {
    url: 'https://api.clubhouse.io/api/beta/epics/76?token=redacted',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { _headers: [Object] },
    ok: false,
    body: PassThrough {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    bodyUsed: true,
    size: 0,`

**Comment by charpeni** [comment]
Hey @janwiberg-dfds!

Could you provide more context on what you're trying to do, and what's missing?
