### ISSUE TITLE
search by external ticket url or ID

### ISSUE THREAD

**Issue by nicks** [clubhouse/clubhouse-lib#70]
I was trying to figure out how to check if there's a clubhouse ticket already associated with a github issue.

SearchStories doesn't seem to work - if I give it a github issue ID, it returns lots of unrelated results

Is there a recommended way to do this?

**Comment by j-martin** [comment]
I don't think their API allows you to do a search by external links. 

https://help.clubhouse.io/hc/en-us/articles/360000046646-Searching-in-Clubhouse-Story-Search

**Comment by charpeni** [comment]
Hey @nicks 👋 

Thanks for reaching out and sorry for the delay.

Unfortunately, we do not have a search operator for external id or URL. But we do have an internal story to track this, I've linked your issue to it.

**Comment by charpeni** [comment]
We recently released an update that enables users to update a Story's external links and to also find all Stories associated to an external link.

Here's the link to the blog post with all the details: https://clubhouse.io/blog/api-v3-update/.

**Comment by nicks** [comment]
Wooo thanks @charpeni ! Excited to try it out!
