### ISSUE TITLE
Using lib in the browser

### ISSUE THREAD

**Issue by molszanski** [clubhouse/clubhouse-lib#72]
I had some issues while trying to use the lib in the browser. 

Both CRA configuration(webpack based) and a rollup based web config have issues with `fetch-everywhere`. 

It just doesn't work. 

Do you want to support browsers with this lib, or you want to limit it to node.js?

**Comment by charpeni** [comment]
Hey @molszanski 👋 

Thanks for reaching out, sorry for the delay I missed that notification.

`clubhouse-lib` isn't directly focused to work in the browser, but having it working would be great.

Can you let us know what's going on with `fetch-everywhere`? We do have a CodeSandbox as a playground working with `clubhouse-lib` here: https://codesandbox.io/s/clubhouse-lib-playground-r447i.

**Comment by molszanski** [comment]
Hey @charpeni! 

I think the codesandbox you've mentioned is node.js environment. 
Here is some other demo: https://codesandbox.io/s/jovial-hodgkin-ko0ek?file=/src/App.tsx

This is commonjs vs modules issues as far as I see it. 

I would try to swap it for isomorphic-fetch or https://www.npmjs.com/package/isomorphic-unfetch

As a workaround, I just wrote a bare minimum client for my needs.

**Comment by charpeni** [comment]
Oh, you're right! 🤦 

It seems related to https://github.com/clubhouse/clubhouse-lib/issues/22.

We don't even use `fetch-everywhere` in the mobile app, we're removing it actually. So, I'm not sure what will be our best option here. We could replace `fetch-everywhere` with a "better" polyfill, or do we need to include it? I'll look into other libraries to see how they solved this across browser, mobile, and node.

Let me know if you have any thoughts.

**Comment by molszanski** [comment]
I would switch to axios because there are less problems with it. The second option would switching to a more compatible polyfill.

**Comment by charpeni** [comment]
Released as part of [`clubhouse-lib@0.11.0`](https://github.com/clubhouse/clubhouse-lib/releases/tag/v0.11.0).
