### ISSUE TITLE
listStories does not include the `description` field.

### ISSUE THREAD

**Issue by mjsz** [clubhouse/clubhouse-lib#80]
Documentation says it should:
https://clubhouse.io/api/rest/v3/#StorySlim

**Comment by mjsz** [comment]
(this may be a bug in the actual v3 API, not this library, but not sure where to file that)

**Comment by charpeni** [comment]
Thanks for flagging this behavior and sorry for the delay!

https://github.com/clubhouse/clubhouse-lib/blob/1c56fad392e1b61f16c56836373878b375d96f8b/src/index.ts#L215-L217

`listStories` is calling [`List Stories`](https://clubhouse.io/api/rest/v3/#List-Stories) which is returning a [`StorySlim`](https://clubhouse.io/api/rest/v3/#StorySlim). By default, the `description` field isn't included but it could be by passing a boolean `includes_description` in the body of `List Stories`.

I'll add a parameter to `listStories` to allow this.

**Comment by charpeni** [comment]
Released as part of [`clubhouse-lib@0.11.0`](https://github.com/clubhouse/clubhouse-lib/releases/tag/v0.11.0).
