### ISSUE TITLE
Stories do not have `external_links` typed

### ISSUE THREAD

**Issue by hdavidzhu** [clubhouse/clubhouse-lib#86]
https://github.com/clubhouse/clubhouse-lib/blob/d85c11de5156a2e4f93f7cf44412b09fb9693e38/src/types.ts#L346

This schema is out-of-date.

**Comment by charpeni** [comment]
Thanks for flagging this!

Replacing `external_tickets` with `external_links` is one of my upcoming tasks.

**Comment by charpeni** [comment]
Released as part of [`clubhouse-lib@0.11.0`](https://github.com/clubhouse/clubhouse-lib/releases/tag/v0.11.0).
