### ISSUE TITLE
fetch-everywhere dependency causing npm audit failure

### ISSUE THREAD

**Issue by naseemkullah** [clubhouse/clubhouse-lib#88]
Hello, it appears that `fetch-everywhere` inhibits a vulnerable dependency, seeing that it has not been updated in a while, is there a replacement such as https://github.com/matthew-andrews/isomorphic-fetch that we can use? If not maybe we could submit a patch to `fetch-everywhere`. Please advise.

**Comment by charpeni** [comment]
Released as part of [`clubhouse-lib@0.11.0`](https://github.com/clubhouse/clubhouse-lib/releases/tag/v0.11.0).
