### ISSUE TITLE
Missing external_links field on type "Story"

### ISSUE THREAD

**Issue by aaronwhite** [clubhouse/clubhouse-lib#90]
The API returns an "external_links" field on Story, but the Typescript type doesn't indicate this. Using ts-ignore allows clients to successfully access the data that is there.

**Comment by charpeni** [comment]
Thanks for flagging this!

Replacing `external_tickets` with `external_links` is one of my upcoming tasks.

**Comment by charpeni** [comment]
Released as part of [`clubhouse-lib@0.11.0`](https://github.com/clubhouse/clubhouse-lib/releases/tag/v0.11.0).
